project:
  type: website
  output-dir: docs

website:
  title: "Ryan Bookstein"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: data.qmd
        text: "Data"
        
format:
  html:
    theme: flatly
    fonts:
      heading: "Poppins"
      body: "Roboto"
    css: styles.css
    toc: true
    
editor: visual



